import { useState, useMemo, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { usePip } from '../../state/PipStore';

interface Props {
  onBack: () => void;
}

export function AfterVisitReceipt({ onBack }: Props) {
  const { activeProfile } = usePip();
  const today = new Date().toISOString().slice(0, 10);
  const [visitDate, setVisitDate] = useState(today);
  const [provider, setProvider] = useState('');
  const [said, setSaid] = useState('');
  const [meds, setMeds] = useState<string[]>([]);
  const [medDraft, setMedDraft] = useState('');
  const [followUp, setFollowUp] = useState('');
  const [watchFor, setWatchFor] = useState<string[]>([]);
  const [wfDraft, setWfDraft] = useState('');
  const [toast, setToast] = useState<string | null>(null);

  useEffect(() => {
    if (!toast) return;
    const t = setTimeout(() => setToast(null), 2200);
    return () => clearTimeout(t);
  }, [toast]);

  const formattedDate = useMemo(
    () =>
      new Date(visitDate + 'T00:00:00').toLocaleDateString('en-US', {
        month: 'long',
        day: 'numeric',
        year: 'numeric',
      }),
    [visitDate],
  );
  const stampDate = useMemo(
    () =>
      new Date(visitDate + 'T00:00:00')
        .toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
        .toUpperCase(),
    [visitDate],
  );
  const isToday = visitDate === today;
  const headlinePrimary = isToday ? "Today's visit." : `${formattedDate}.`;
  const hasAnyContent = !!said || meds.length > 0 || !!followUp || watchFor.length > 0;
  const displayHeadline = hasAnyContent ? headlinePrimary : 'Nothing captured yet.';

  const addChip = (val: string, list: string[], setter: (v: string[]) => void, clear: () => void) => {
    const v = val.trim();
    if (!v) return;
    setter([...list, v]);
    clear();
  };

  const removeChip = (idx: number, list: string[], setter: (v: string[]) => void) => {
    setter(list.filter((_, i) => i !== idx));
  };

  const onShare = async () => {
    const lines: string[] = [];
    lines.push(`After-visit notes for ${activeProfile?.firstName ?? 'patient'}`);
    lines.push(formattedDate + (provider ? `, with ${provider}` : ''));
    lines.push('');
    if (said) {
      lines.push('What they said');
      lines.push(said);
      lines.push('');
    }
    if (meds.length) {
      lines.push('Prescribed');
      meds.forEach((m) => lines.push(`• ${m}`));
      lines.push('');
    }
    if (followUp) {
      lines.push('Follow up');
      lines.push(followUp);
      lines.push('');
    }
    if (watchFor.length) {
      lines.push('Watch for');
      watchFor.forEach((w) => lines.push(`• ${w}`));
      lines.push('');
    }
    lines.push('Generated by Pip');
    const text = lines.join('\n');
    try {
      if (typeof navigator !== 'undefined' && (navigator as Navigator).share) {
        await (navigator as Navigator).share({ title: 'After-visit notes', text });
      } else if (navigator.clipboard) {
        await navigator.clipboard.writeText(text);
        setToast('Copied. Paste anywhere.');
      }
    } catch {
      // user cancelled share
    }
  };

  return (
    <div
      className="w-full h-full overflow-y-auto pip-no-scrollbar"
      style={{ background: '#E8E2CC', paddingBottom: 130 }}
    >
      <style>{`
        .pip-no-scrollbar::-webkit-scrollbar { width: 0; height: 0; }
        .pip-no-scrollbar { scrollbar-width: none; -ms-overflow-style: none; }
        @media print {
          .pip-no-print { display: none !important; }
          body, html { background: #FFFFFF !important; }
          #receipt-printable { box-shadow: none !important; border: 0.5px solid rgba(0,0,0,0.12); }
        }
      `}</style>

      <header
        className="px-5 flex items-center pip-no-print"
        style={{ paddingTop: 'max(env(safe-area-inset-top, 0px), 18px)', paddingBottom: 12 }}
      >
        <button
          onClick={onBack}
          className="flex items-center gap-1.5 active:opacity-70"
          style={{ color: 'rgba(61,64,91,0.7)', fontFamily: 'Inter', fontWeight: 500, fontSize: 14 }}
        >
          <svg
            width="16"
            height="16"
            viewBox="0 0 16 16"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
          >
            <path d="M10 12L5 8l5-4" />
          </svg>
          Back
        </button>
      </header>

      <div className="px-5 pip-no-print">
        <h1
          style={{
            fontFamily: 'var(--font-serif)',
            fontVariationSettings: '"opsz" 96, "SOFT" 50',
            fontWeight: 400,
            fontSize: 'clamp(36px, 8.8vw, 44px)',
            lineHeight: 0.95,
            letterSpacing: '-0.03em',
            color: '#3D405B',
            margin: 0,
          }}
        >
          Before you <span style={{ fontStyle: 'italic' }}>forget</span>.
        </h1>
        <p
          style={{
            fontFamily: 'var(--font-serif)',
            fontStyle: 'italic',
            fontVariationSettings: '"opsz" 14',
            fontSize: 14.5,
            color: 'rgba(61,64,91,0.6)',
            margin: '8px 0 0',
            lineHeight: 1.45,
            letterSpacing: '-0.005em',
          }}
        >
          Capture it now, while it's fresh.
        </p>
      </div>

      {/* Form */}
      <div className="px-5 mt-7 flex flex-col pip-no-print" style={{ gap: 18 }}>
        <FieldRow>
          <FieldLabel>Date</FieldLabel>
          <input
            type="date"
            value={visitDate}
            onChange={(e) => setVisitDate(e.target.value)}
            className="bg-transparent outline-none"
            style={fieldInput}
          />
        </FieldRow>
        <FieldRow>
          <FieldLabel>Provider</FieldLabel>
          <input
            value={provider}
            onChange={(e) => setProvider(e.target.value)}
            placeholder="Dr. Smith"
            className="bg-transparent outline-none"
            style={fieldInput}
          />
        </FieldRow>
        <FieldRow>
          <FieldLabel>What they said</FieldLabel>
          <textarea
            value={said}
            onChange={(e) => setSaid(e.target.value)}
            placeholder="Diagnosis, explanation, next steps."
            className="bg-transparent outline-none resize-none"
            style={{ ...fieldInput, minHeight: 92, lineHeight: 1.5 }}
          />
        </FieldRow>
        <FieldRow>
          <FieldLabel>Prescribed</FieldLabel>
          <ChipInput
            draft={medDraft}
            setDraft={setMedDraft}
            list={meds}
            onAdd={() => addChip(medDraft, meds, setMeds, () => setMedDraft(''))}
            onRemove={(i) => removeChip(i, meds, setMeds)}
            placeholder="Amoxicillin 500mg"
          />
        </FieldRow>
        <FieldRow>
          <FieldLabel>Follow up</FieldLabel>
          <input
            value={followUp}
            onChange={(e) => setFollowUp(e.target.value)}
            placeholder="In two weeks"
            className="bg-transparent outline-none"
            style={fieldInput}
          />
        </FieldRow>
        <FieldRow>
          <FieldLabel>Watch for</FieldLabel>
          <ChipInput
            draft={wfDraft}
            setDraft={setWfDraft}
            list={watchFor}
            onAdd={() => addChip(wfDraft, watchFor, setWatchFor, () => setWfDraft(''))}
            onRemove={(i) => removeChip(i, watchFor, setWatchFor)}
            placeholder="Fever returning"
          />
        </FieldRow>
      </div>

      {/* Paper preview */}
      <motion.article
        id="receipt-printable"
        initial={{ opacity: 0, y: 24, rotateX: 5 }}
        animate={{ opacity: 1, y: 0, rotateX: 0 }}
        transition={{ duration: 0.75, ease: [0.22, 0.61, 0.36, 1] }}
        className="mx-4 mt-8 relative"
        style={{
          background: '#FBF8EC',
          borderRadius: 4,
          padding: '36px 28px 28px',
          color: '#1A1A1A',
          boxShadow:
            '0 1px 0 rgba(255,255,255,0.85) inset, 0 28px 60px -20px rgba(61,64,91,0.32), 0 2px 0 rgba(0,0,0,0.04)',
          transformOrigin: 'top center',
        }}
      >
        <div
          aria-hidden
          style={{
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            height: 6,
            background:
              'repeating-linear-gradient(90deg, transparent 0, transparent 6px, rgba(0,0,0,0.05) 6px, rgba(0,0,0,0.05) 7px)',
          }}
        />

        {/* Letterhead */}
        <div
          className="flex items-start justify-between relative"
          style={{ borderBottom: '0.5px solid rgba(26,26,26,0.18)', paddingBottom: 18 }}
        >
          <div style={{ flex: 1, paddingRight: 70 }}>
            <p
              style={{
                fontFamily: 'var(--font-serif)',
                fontVariationSettings: '"opsz" 144, "SOFT" 50',
                fontStyle: 'italic',
                fontWeight: 400,
                fontSize: 44,
                color: '#3D405B',
                letterSpacing: '-0.035em',
                lineHeight: 0.95,
                margin: 0,
              }}
            >
              Pip
            </p>
            <p
              style={{
                fontFamily: 'var(--font-serif)',
                fontStyle: 'italic',
                fontVariationSettings: '"opsz" 18',
                fontSize: 13,
                color: 'rgba(26,26,26,0.55)',
                marginTop: 2,
                letterSpacing: '-0.005em',
              }}
            >
              After-visit notes
            </p>
          </div>
          <div className="text-right" style={{ paddingLeft: 12 }}>
            <p
              style={{
                fontFamily: 'var(--font-serif)',
                fontVariationSettings: '"opsz" 36',
                fontWeight: 500,
                fontSize: 18,
                color: '#1A1A1A',
                lineHeight: 1.1,
                letterSpacing: '-0.012em',
                margin: 0,
              }}
            >
              {activeProfile?.firstName ?? '—'}
            </p>
            {provider && (
              <p
                style={{
                  fontFamily: 'var(--font-serif)',
                  fontStyle: 'italic',
                  fontVariationSettings: '"opsz" 14',
                  fontSize: 11.5,
                  color: 'rgba(26,26,26,0.55)',
                  marginTop: 3,
                  letterSpacing: '-0.003em',
                }}
              >
                with {provider}
              </p>
            )}
            <p
              style={{
                fontFamily: 'var(--font-serif)',
                fontStyle: 'italic',
                fontVariationSettings: '"opsz" 11',
                fontSize: 10.5,
                color: 'rgba(26,26,26,0.42)',
                marginTop: provider ? 6 : 4,
                letterSpacing: '-0.003em',
              }}
            >
              {formattedDate}
            </p>
          </div>

          {/* Wax-seal stamp */}
          <motion.div
            initial={{ opacity: 0, scale: 0.6, rotate: -22 }}
            animate={{ opacity: 1, scale: 1, rotate: -8 }}
            transition={{ delay: 0.9, duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
            aria-hidden
            style={{
              position: 'absolute',
              right: -6,
              bottom: -10,
              width: 68,
              height: 68,
              pointerEvents: 'none',
            }}
          >
            <svg width="68" height="68" viewBox="0 0 64 64" fill="none">
              <defs>
                <path id="receipt-arc-top" d="M 9 32 A 23 23 0 0 1 55 32" />
                <path id="receipt-arc-bottom" d="M 9 32 A 23 23 0 0 0 55 32" />
              </defs>
              <circle
                cx="32"
                cy="32"
                r="27"
                stroke="#B0473A"
                strokeWidth="1.4"
                opacity="0.55"
                fill="none"
                strokeDasharray="2 1.6"
              />
              <circle cx="32" cy="32" r="22" stroke="#B0473A" strokeWidth="1" opacity="0.5" fill="none" />
              <text fill="#B0473A" opacity="0.75" fontFamily="Inter" fontWeight="600" fontSize="4.6" letterSpacing="1.2">
                <textPath href="#receipt-arc-top" startOffset="50%" textAnchor="middle">
                  PIP · RECEIPT
                </textPath>
              </text>
              <text fill="#B0473A" opacity="0.6" fontFamily="Inter" fontWeight="500" fontSize="4.2" letterSpacing="1.2">
                <textPath href="#receipt-arc-bottom" startOffset="50%" textAnchor="middle">
                  FOR THE PATIENT
                </textPath>
              </text>
              <text
                x="32"
                y="35"
                textAnchor="middle"
                fill="#B0473A"
                opacity="0.82"
                fontFamily="var(--font-serif)"
                fontStyle="italic"
                fontSize="9"
                fontWeight="500"
              >
                {stampDate}
              </text>
            </svg>
          </motion.div>
        </div>

        {/* Headline with drop cap */}
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.35, duration: 0.55, ease: [0.22, 1, 0.36, 1] }}
          style={{ marginTop: 26 }}
        >
          <p
            style={{
              fontFamily: 'var(--font-serif)',
              fontVariationSettings: '"opsz" 96, "SOFT" 50',
              fontStyle: hasAnyContent ? 'normal' : 'italic',
              fontWeight: 400,
              fontSize: 27,
              lineHeight: 1.15,
              letterSpacing: '-0.022em',
              color: '#1A1A1A',
              margin: 0,
            }}
          >
            <span
              style={{
                float: 'left',
                fontFamily: 'var(--font-serif)',
                fontVariationSettings: '"opsz" 144, "SOFT" 60',
                fontStyle: 'italic',
                fontWeight: 400,
                fontSize: 64,
                lineHeight: 0.86,
                color: '#B0473A',
                marginRight: 6,
                marginTop: 2,
                paddingRight: 2,
              }}
            >
              {displayHeadline.charAt(0)}
            </span>
            {displayHeadline.slice(1)}
          </p>
        </motion.div>

        {said && (
          <Section title="What they said">
            <p
              style={{
                fontFamily: 'var(--font-serif)',
                fontVariationSettings: '"opsz" 24',
                fontSize: 15.5,
                lineHeight: 1.55,
                color: '#1A1A1A',
                letterSpacing: '-0.005em',
                margin: 0,
                whiteSpace: 'pre-wrap',
              }}
            >
              {said}
            </p>
          </Section>
        )}

        {meds.length > 0 && (
          <Section title="Prescribed">
            <ul className="flex flex-col" style={{ gap: 6 }}>
              {meds.map((m, i) => (
                <li key={i} className="flex items-baseline gap-2" style={paperBody}>
                  <span
                    aria-hidden
                    style={{
                      width: 3,
                      height: 3,
                      borderRadius: 999,
                      background: '#1A1A1A',
                      display: 'inline-block',
                      marginBottom: 3,
                      flexShrink: 0,
                    }}
                  />
                  <span>{m}</span>
                </li>
              ))}
            </ul>
          </Section>
        )}

        {followUp && (
          <Section title="Follow up">
            <p style={{ ...paperBody, margin: 0 }}>{followUp}</p>
          </Section>
        )}

        {watchFor.length > 0 && (
          <Section title="Watch for">
            <ul className="flex flex-col" style={{ gap: 6 }}>
              {watchFor.map((w, i) => (
                <li key={i} className="flex items-baseline gap-2" style={paperBody}>
                  <span
                    aria-hidden
                    style={{
                      width: 4,
                      height: 4,
                      borderRadius: 999,
                      background: '#E07A5F',
                      display: 'inline-block',
                      marginBottom: 3,
                      flexShrink: 0,
                    }}
                  />
                  <span>{w}</span>
                </li>
              ))}
            </ul>
          </Section>
        )}

        <div style={{ marginTop: 28, paddingTop: 14, borderTop: '0.5px solid rgba(26,26,26,0.18)' }}>
          <p
            style={{
              fontFamily: 'var(--font-serif)',
              fontStyle: 'italic',
              fontVariationSettings: '"opsz" 11',
              fontSize: 10.5,
              lineHeight: 1.55,
              color: 'rgba(26,26,26,0.5)',
            }}
          >
            Not medical advice. For emergencies, call 911.
          </p>
          <p
            style={{
              fontFamily: 'var(--font-serif)',
              fontStyle: 'italic',
              fontVariationSettings: '"opsz" 14',
              fontSize: 11,
              color: 'rgba(26,26,26,0.4)',
              marginTop: 6,
              letterSpacing: '-0.005em',
            }}
          >
            pip.health
          </p>
        </div>
      </motion.article>

      {/* Floating action bar */}
      <motion.div
        initial={{ opacity: 0, y: 24 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 1.0, duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
        className="fixed left-1/2 pip-no-print"
        style={{
          bottom: 'max(env(safe-area-inset-bottom, 0px), 22px)',
          transform: 'translateX(-50%)',
          background: 'rgba(251,248,236,0.92)',
          backdropFilter: 'blur(14px)',
          WebkitBackdropFilter: 'blur(14px)',
          borderRadius: 999,
          border: '0.5px solid rgba(61,64,91,0.12)',
          boxShadow: '0 2px 4px rgba(0,0,0,0.04), 0 16px 36px rgba(120,110,90,0.16)',
          padding: 6,
          display: 'flex',
          alignItems: 'center',
          gap: 2,
          zIndex: 50,
        }}
      >
        <FloatingAction
          onClick={onShare}
          icon={
            <svg
              width="14"
              height="14"
              viewBox="0 0 16 16"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.6"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="M11 4L8 1 5 4M8 1v9M3 9v4a1 1 0 001 1h8a1 1 0 001-1V9" />
            </svg>
          }
          label="Share"
        />
        <span style={{ width: 0.5, height: 18, background: 'rgba(61,64,91,0.15)' }} />
        <FloatingAction
          onClick={() => window.print()}
          icon={
            <svg
              width="14"
              height="14"
              viewBox="0 0 16 16"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.6"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="M3 9V2h10v7M3 13h10v-4H3zM5 6h6" />
            </svg>
          }
          label="Print · PDF"
          primary
        />
      </motion.div>

      <AnimatePresence>
        {toast && (
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 16 }}
            transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
            className="fixed left-1/2 pip-no-print"
            style={{
              bottom: 'calc(max(env(safe-area-inset-bottom, 0px), 22px) + 68px)',
              transform: 'translateX(-50%)',
              background: '#3D405B',
              color: '#FBF8EC',
              fontFamily: 'Inter',
              fontWeight: 500,
              fontSize: 12,
              padding: '8px 14px',
              borderRadius: 999,
              boxShadow: '0 12px 28px rgba(61,64,91,0.28)',
              zIndex: 60,
            }}
          >
            {toast}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

function FieldRow({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex flex-col" style={{ gap: 6 }}>
      {children}
    </div>
  );
}

function FieldLabel({ children }: { children: React.ReactNode }) {
  return (
    <span
      style={{
        fontFamily: 'var(--font-serif)',
        fontStyle: 'italic',
        fontVariationSettings: '"opsz" 18',
        fontSize: 13,
        color: 'rgba(61,64,91,0.62)',
        letterSpacing: '-0.005em',
        paddingLeft: 4,
      }}
    >
      {children}
    </span>
  );
}

const fieldInput: React.CSSProperties = {
  background: '#FBF8EC',
  borderRadius: 14,
  border: '0.5px solid rgba(61,64,91,0.12)',
  padding: '12px 14px',
  fontFamily: 'var(--font-serif)',
  fontVariationSettings: '"opsz" 18',
  fontSize: 15.5,
  lineHeight: 1.4,
  color: '#3D405B',
  letterSpacing: '-0.005em',
  width: '100%',
  boxShadow: '0 1px 0 rgba(255,255,255,0.6) inset',
};

function ChipInput({
  draft,
  setDraft,
  list,
  onAdd,
  onRemove,
  placeholder,
}: {
  draft: string;
  setDraft: (v: string) => void;
  list: string[];
  onAdd: () => void;
  onRemove: (i: number) => void;
  placeholder: string;
}) {
  return (
    <div>
      <div className="flex" style={{ gap: 8 }}>
        <input
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === 'Enter') {
              e.preventDefault();
              onAdd();
            }
          }}
          placeholder={placeholder}
          className="bg-transparent outline-none flex-1"
          style={fieldInput}
        />
        <button
          onClick={onAdd}
          style={{
            background: '#3D405B',
            color: '#FBF8EC',
            fontFamily: 'Inter',
            fontWeight: 600,
            fontSize: 13,
            padding: '0 18px',
            borderRadius: 14,
            height: 44,
            flexShrink: 0,
            letterSpacing: '-0.005em',
          }}
        >
          Add
        </button>
      </div>
      <AnimatePresence initial={false}>
        {list.length > 0 && (
          <motion.div
            initial={{ opacity: 0, y: -4 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -4 }}
            className="flex flex-wrap"
            style={{ gap: 6, marginTop: 8 }}
          >
            {list.map((m, i) => (
              <motion.button
                key={`${m}-${i}`}
                layout
                initial={{ scale: 0.85, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                exit={{ scale: 0.85, opacity: 0 }}
                onClick={() => onRemove(i)}
                className="flex items-center"
                style={{
                  background: 'rgba(224,122,95,0.12)',
                  border: '0.5px solid rgba(224,122,95,0.28)',
                  color: '#B0473A',
                  fontFamily: 'var(--font-serif)',
                  fontStyle: 'italic',
                  fontVariationSettings: '"opsz" 14',
                  fontSize: 13,
                  padding: '5px 10px 5px 12px',
                  borderRadius: 999,
                  letterSpacing: '-0.005em',
                  gap: 6,
                }}
              >
                {m}
                <svg
                  width="10"
                  height="10"
                  viewBox="0 0 10 10"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="1.5"
                  strokeLinecap="round"
                  opacity="0.6"
                >
                  <path d="M2 2l6 6M8 2l-6 6" />
                </svg>
              </motion.button>
            ))}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <motion.section
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4, ease: [0.22, 1, 0.36, 1] }}
      style={{ marginTop: 26 }}
    >
      <div
        className="flex items-baseline"
        style={{
          marginBottom: 12,
          borderBottom: '0.5px solid rgba(26,26,26,0.18)',
          paddingBottom: 6,
        }}
      >
        <h2
          style={{
            fontFamily: 'var(--font-serif)',
            fontStyle: 'italic',
            fontVariationSettings: '"opsz" 24, "SOFT" 40',
            fontWeight: 400,
            fontSize: 15,
            color: '#3D405B',
            letterSpacing: '-0.008em',
            margin: 0,
            lineHeight: 1.1,
          }}
        >
          {title}
        </h2>
      </div>
      {children}
    </motion.section>
  );
}

function FloatingAction({
  onClick,
  icon,
  label,
  primary = false,
}: {
  onClick: () => void;
  icon: React.ReactNode;
  label: string;
  primary?: boolean;
}) {
  return (
    <motion.button
      onClick={onClick}
      whileTap={{ scale: 0.96 }}
      whileHover={{ scale: 1.03 }}
      transition={{ type: 'spring', stiffness: 320, damping: 24 }}
      className="flex items-center"
      style={{
        gap: 6,
        padding: '8px 14px',
        borderRadius: 999,
        background: primary ? '#3D405B' : 'transparent',
        color: primary ? '#FBF8EC' : '#3D405B',
        fontFamily: 'Inter',
        fontWeight: 600,
        fontSize: 12,
        letterSpacing: '0.01em',
        cursor: 'pointer',
      }}
    >
      {icon}
      {label}
    </motion.button>
  );
}

const paperBody: React.CSSProperties = {
  fontFamily: 'Inter',
  fontWeight: 400,
  fontSize: 13.5,
  lineHeight: 1.55,
  color: '#1A1A1A',
};
